from pattern_utiles.pattern_dictionary import PatternTypeDictionary


def kernel_code_generator(pattern_type_dictionary: PatternTypeDictionary):
    number_of_patterns = len(pattern_type_dictionary.pattern_bin_to_id)

    file = ""
    file += "__global__ void SpmvComplexPatternDecomposeByRowSeperated( \n"
    file += "   swiftware::compression::MixedFormatGPU<float> *mf, float *dX, float *dY) {\n"
    file += f"  int j = blockIdx.x / {number_of_patterns};\n"
    file += f"  int i = blockIdx.x % {number_of_patterns};\n\n"

    file += "  switch (i) {\n"
    for i, pattern in pattern_type_dictionary.id_to_patten_bin.items():
        nnz_number = pattern_type_dictionary.pattern_id_to_number_of_nnz(i)
        file += f"    case {i}:\n"
        file += (f"      PatternWith{nnz_number}NNZByRowPanelFull("
                 f"mf->cf[{i}]->RPP, mf->cf[{i}]->NPP, mf->cf[{i}]->NNZ, mf->cf[{i}]->CB, dX, dY, j ")
        for x in range(len(pattern)):
            if '1' == pattern[x]:
                file += f", {x}"
        file += ");\n"
        file += "      break;\n"

    file += "  }\n"
    file += "}\n"

    return file


def class_code_generator(m, number_of_warp):
    if number_of_warp <= 0:
        number_of_warp = 1
    file = ""
    file += "class SpMVMixePatternDecomposeByRowSeperated : public SpMVSerialFloat {\n"
    file += "\n"
    file += "protected:\n"
    file += "  float *x;\n"
    file += "\n"
    file += "  float *dX, *dY, *dY1, *dY2;\n"
    file += "  swiftware::compression::MixedFormatGPU<float> *mf;\n"
    file += "\n"
    file += "  float alpha = 1.0f;\n"
    file += "\n"
    file += "  TensorInputsMixed *InT;\n"
    file += "\n"
    file += "  bool verify(double &Error) override {\n"
    file += "    bool retValue = true;\n"
    file += "\n"
    file += "    double infNorm = 0;\n"
    file += "    for (int i = 0; i < InTensor->M - 4; ++i) {\n"
    file += "      if (std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]) > infNorm) {\n"
    file += "        infNorm = std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]);\n"
    file += "      }\n"
    file += "    }\n"
    file += "    Error = (double)infNorm;\n"
    file += "    if (infNorm > InTensor->Threshold) {\n"
    file += "      retValue = false;\n"
    file += "    }\n"
    file += "    return retValue;\n"
    file += "  }\n"
    file += "\n"
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += "\n"
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "\n"
    file += "    t1.startGPU();\n"
    file += "    // lunch kernel\n"
    file += "\n"
    file += "    SpmvComplexPatternDecomposeByRowSeperated<<<\n"
    file += f"        (InT->MixedFormat->cf[0]->nrpp - 1) * {(2 ** m) - 1}, {number_of_warp * 32}>>>(mf, dX, dY);\n"
    file += "\n"
    file += "    t1.stopGPU(\"\");\n"
    file += "\n"
    file += "    cudaMemcpy(this->OutTensor->Dx, dY, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyDeviceToHost);\n"
    file += "    cudaMemset(dY, 0, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "\n"
    file += "    return t1;\n"
    file += "  }\n"
    file += "\n"
    file += "public:\n"
    file += "  SpMVMixePatternDecomposeByRowSeperated(TensorInputsMixed *In1,\n"
    file += "                                         swiftware::benchmark::Stats *Stat1)\n"
    file += "      : SpMVSerialFloat(In1, Stat1), InT(In1) {\n"
    file += "\n"
    file += "    x = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->nnz));\n"
    file += "    for (int i = 0; i < In1->ACsr->nnz; i++) {\n"
    file += "      x[i] = static_cast<float>(In1->ACsr->x[i]);\n"
    file += "    }\n"
    file += "\n"
    file += "    cudaMalloc((void **)&dX, InTensor->N * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY, InTensor->M * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY1, InTensor->M * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY2, InTensor->M * sizeof(float));\n"
    file += "    //\n"
    file += "    cudaMemset(dY, 0, InTensor->M * sizeof(float));\n"
    file += "    cudaMemset(dY1, 0, InTensor->M * sizeof(float));\n"
    file += "    cudaMemset(dY2, 0, InTensor->M * sizeof(float));\n"
    file += "    cudaMemcpy(dX, this->InTensor->Bx, InTensor->N * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "    mf = allocateAndCopyMixedFormat(In1->MixedFormat);\n"
    file += "  };\n"
    file += "\n"
    file += "  ~SpMVMixePatternDecomposeByRowSeperated() {\n"
    file += "    //    cudaFree(dX);\n"
    file += "    //    cudaFree(dY);\n"
    file += "  }\n"
    file += "};\n"

    return file


def codelet_code_generator(m):
    file = ""
    for i in range(1, m + 1):
        pack_size = 32 // i
        file += f"__device__ void PatternWith{i}NNZByRowPanelFull(int *RPP, int *NPP, float *NNZ,\n"
        file += "                                              int *CB, float *dx, float *dy, int i "
        for x in range(i):
            file += f", int offset{x}"
        file += ") {\n\n"
        file += "  int blockSize = blockDim.x;\n"
        file += "  int thread_id_in_warp = threadIdx.x % 32;\n"
        file += "  int warp_id = threadIdx.x / 32;\n"
        file += "\n\n"
        file += ""
        file += "  int rowStart_all = RPP[i];\n"
        file += "  int rowEnd_all = RPP[i + 1];\n"
        file += f"  int number_of_packs = (rowEnd_all - rowStart_all) / {pack_size};\n"
        file += "  if (rowEnd_all - rowStart_all == 0) {\n"
        file += "    return;\n"
        file += "  }\n\n"
        file += "  number_of_packs = number_of_packs == 0 ? 1 : number_of_packs;\n"
        file += "  int number_of_warps = blockSize / 32;\n"
        file += "  int pack_share = (number_of_packs + number_of_warps - 1) / number_of_warps;\n"
        file += f"  int warp_share = pack_share * {pack_size};\n"
        file += "  int rowStart = rowStart_all + warp_id * warp_share;\n"
        file += "  int rowEnd = rowStart + warp_share;\n"
        file += "  rowEnd = rowEnd > rowEnd_all ? rowEnd_all : rowEnd;\n"
        file += "  rowEnd = warp_id == number_of_warps - 1 && rowEnd < rowEnd_all ? rowEnd_all : rowEnd;\n"

        file += f"  int t_nnz = NPP[i] + warp_id * warp_share * {i};\n"
        file += "  float sum_all = 0.0f;\n"

        file += f"  int j = rowStart;\n"
        file += f"  for ( j ; j < rowEnd - {pack_size - 1}; j += {pack_size}) {{\n"
        file += f"    float nnz = (thread_id_in_warp < {pack_size * i}) ? NNZ[t_nnz + thread_id_in_warp] : 0;\n"
        file += "    float B = 0.0f;\n"
        file += f"    B = dx[CB[j + thread_id_in_warp / {i}]];\n"
        file += "\n"
        file += "    sum_all += nnz * B;\n"

        file += f"    t_nnz += {pack_size * i};\n"
        file += "  }\n"

        file += "  int tail = rowEnd - j;\n"
        file += f"  int rest_nnz = {i} * tail; \n"

        file += "  if (thread_id_in_warp < rest_nnz && tail > 0) {\n"
        file += "    float nnz = NNZ[t_nnz + thread_id_in_warp];\n"
        file += "    float B = 0.0f;\n"
        file += f"    B = dx[CB[j + thread_id_in_warp / {i}]];\n"
        file += "    sum_all += nnz * B;\n"
        file += "  }\n"

        temp_text = ""
        start_reduction_point = i
        encounterd_threads = pack_size * i
        end_thread = (pack_size - 1) * i
        pack_size_temp = pack_size
        temp_counter = 0
        off_set_end = 1

        if pack_size_temp % 2 == 1:
            file += f"  float temp_sum{temp_counter} = sum_all;\n"
            file += f"  sum_all += __shfl_down_sync(0xFFFFFFFF, sum_all, {start_reduction_point});\n"
            temp_text += f" sum_all += __shfl_down_sync(0xFFFFFFFF, temp_sum{temp_counter}, {end_thread});\n"
            temp_counter += 1
            start_reduction_point *= 2
            pack_size_temp = pack_size_temp // 2
            end_thread = end_thread - 2 * i

        while start_reduction_point <= encounterd_threads / 2:
            if pack_size_temp % 2 == 1 and start_reduction_point != 1:
                file += f"  float temp_sum{temp_counter} = sum_all;\n"
                file += f"  sum_all += __shfl_down_sync(0xFFFFFFFF, sum_all, {start_reduction_point});\n"
                temp_text += f"  sum_all += __shfl_down_sync(0xFFFFFFFF, temp_sum{temp_counter}, {end_thread});\n"
                pack_size_temp = pack_size_temp // 2
                start_reduction_point *= 2
                end_thread = end_thread - 2 * i
                temp_counter += 1
            else:
                file += f"  sum_all += __shfl_down_sync(0xFFFFFFFF, sum_all, {start_reduction_point});" + "\n"
                start_reduction_point *= 2
                pack_size_temp = pack_size_temp // 2
                off_set_end += 1
                end_thread = end_thread - i

        file += temp_text
        file += f"  if (thread_id_in_warp == 0) {{\n"
        file += f"      atomicAdd(&dy[i * {m} + offset0], sum_all);\n"
        file += "  }\n"
        p = 1
        while p < i:
            file += f"  else if (thread_id_in_warp == {p}){{\n"
            file += f"    atomicAdd(&dy[i * {m} + offset{p}], sum_all);\n"
            file += "  }\n"
            p += 1
        file += "}\n"
    return file


def base_code_generator(codelet_file, kernel_file, class_file):
    file = ""
    file += "#ifndef COMPRESSED_TENSOR_ALGEBRA_SPMV_DEMO_GPU_UTILS_H\n"
    file += "#define COMPRESSED_TENSOR_ALGEBRA_SPMV_DEMO_GPU_UTILS_H\n"
    file += "\n"
    file += "#include \"Logger.h\"\n"
    file += "#include \"SWTensorBench.h\"\n"
    file += "#include \"aggregation/def.h\"\n"
    file += "#include \"compressed_format/CompressedFormat.h\"\n"
    file += "#include \"iostream\"\n"
    file += "#include <cooperative_groups.h>\n"
    file += "#include <cstdlib>\n"
    file += "#include <cublas_v2.h>\n"
    file += "#include <cuda/pipeline>\n"
    file += "#include <cuda_runtime.h>\n"
    file += "#include <cuda_runtime_api.h> // cudaMalloc, cudaMemcpy, etc.\n"
    file += "#include <cusparse.h>         // cusparseSpMV\n"
    file += "#include <stdio.h>            // printf\n"
    file += "#include <stdlib.h>           // EXIT_FAILURE         // EXIT_FAILURE\n"
    file += "\n"
    file += "// CUDA API error checking\n"
    file += "#define CUDA_CHECK(err)                                                        \\\n"
    file += "  do {                                                                         \\\n"
    file += "    cudaError_t err_ = (err);                                                  \\\n"
    file += "    if (err_ != cudaSuccess) {                                                 \\\n"
    file += "      std::printf(\"CUDA error %d at %s:%d\\n\", err_, __FILE__, __LINE__);       \\\n"
    file += "      throw std::runtime_error(\"CUDA error\");                                  \\\n"
    file += "    }                                                                          \\\n"
    file += "  } while (0)\n"
    file += "\n"
    file += "namespace cg = cooperative_groups;\n"
    file += "// cublas API error checking\n"
    file += "#define CUBLAS_CHECK(err)                                                      \\\n"
    file += "  do {                                                                         \\\n"
    file += "    cublasStatus_t err_ = (err);                                               \\\n"
    file += "    if (err_ != CUBLAS_STATUS_SUCCESS) {                                       \\\n"
    file += "      std::printf(\"cublas error %d at %s:%d\\n\", err_, __FILE__, __LINE__);     \\\n"
    file += "      throw std::runtime_error(\"cublas error\");                                \\\n"
    file += "    }                                                                          \\\n"
    file += "  } while (0)\n"
    file += "\n"
    file += "void copyCSR(sym_lib::CSR *A, sym_lib::CSR *ACsr) {\n"
    file += "  ACsr->m = A->m;\n"
    file += "  ACsr->n = A->n;\n"
    file += "  ACsr->nnz = A->nnz;\n"
    file += "  for (int i = 0; i < A->m + 1; ++i) {\n"
    file += "    ACsr->p[i] = A->p[i];\n"
    file += "  }\n"
    file += "  for (int i = 0; i < A->m; ++i) {\n"
    file += "    for (int j = A->p[i]; j < A->p[i + 1]; ++j) {\n"
    file += "      ACsr->x[j] = A->x[j];\n"
    file += "      ACsr->i[j] = A->i[j];\n"
    file += "    }\n"
    file += "  }\n"
    file += "}\n"
    file += "\n"
    file += "void generateDenseFromCsr(int M, int N, sym_lib::CSR *A, float *X) {\n"
    file += "  for (int i = 0; i < M; ++i) {\n"
    file += "    for (int j = 0; j < N; ++j) {\n"
    file += "      X[i * N + j] = 0.0;\n"
    file += "    }\n"
    file += "  }\n"
    file += "  for (int i = 0; i < M; ++i) {\n"
    file += "    for (int j = A->p[i]; j < A->p[i + 1]; ++j) {\n"
    file += "      X[i * N + A->i[j]] = A->x[j];\n"
    file += "    }\n"
    file += "  }\n"
    file += "}\n"
    file += "\n"
    file += "template <typename T>\n"
    file += "struct TensorOutputs : public swiftware::benchmark::Outputs<T> {\n"
    file += "  int M;\n"
    file += "  T *Dx;\n"
    file += "\n"
    file += "  TensorOutputs(int M) : M(M) { Dx = new T[M](); }\n"
    file += "\n"
    file += "  ~TensorOutputs() { delete[] Dx; }\n"
    file += "\n"
    file += "  void printDx() {\n"
    file += "    std::cout << \"\\n Dx:\\n\";\n"
    file += "    //    printDense<T>(M, 1, Dx);\n"
    file += "    std::cout << \"\\n\";\n"
    file += "  }\n"
    file += "\n"
    file += "  void reset() { std::fill_n(Dx, M, 0.0); }\n"
    file += "};\n"
    file += "\n"
    file += "void spmv_csr_float(int n, const int *Ap, const int *Ai, const float *Ax,\n"
    file += "                    const float *x, float *y) {\n"
    file += "\n"
    file += "  for (int i = 0; i < n; i++) {\n"
    file += "    double sum = 0.0;\n"
    file += "    for (int j = Ap[i]; j < Ap[i + 1]; j++) {\n"
    file += "      int col_index = Ai[j];\n"
    file += "      double value = Ax[j];\n"
    file += "      sum += value * x[col_index];\n"
    file += "    }\n"
    file += "    y[i] += sum;\n"
    file += "  }\n"
    file += "}\n"
    file += "\n"
    file += "struct TensorInputsFloat : public swiftware::benchmark::Inputs<float> {\n"
    file += "  int M, N;\n"
    file += "  sym_lib::CSR *ACsr;\n"
    file += "\n"
    file += "  float *Bx;\n"
    file += "  float *CorrectMul;\n"
    file += "  bool IsSolProvided;\n"
    file += "\n"
    file += "  TensorInputsFloat(int M1, int N1, sym_lib::CSR *A1, int NumThreads1,\n"
    file += "                    int NumTrial1, std::string ExpN)\n"
    file += "      : swiftware::benchmark::Inputs<float>(NumTrial1, NumThreads1, ExpN) {\n"
    file += "    M = M1;\n"
    file += "    N = N1;\n"
    file += "    if (A1 != nullptr)\n"
    file += "      ACsr = new sym_lib::CSR(M, N, A1->nnz);\n"
    file += "\n"
    file += "    copyCSR(A1, ACsr);\n"
    file += "    IsSolProvided = false;\n"
    file += "    swiftware::benchmark::Inputs<float>::Threshold = 1e-6;\n"
    file += "  }\n"
    file += "\n"
    file += "  ~TensorInputsFloat() {\n"
    file += "    free(CorrectSol);\n"
    file += "    free(CorrectMul);\n"
    file += "    free(Bx);\n"
    file += "    delete ACsr;\n"
    file += "  }\n"
    file += "};\n"

    file += "class SpMVSerialFloat : public swiftware::benchmark::SWTensorBench<float> {\n"
    file += "protected:\n"
    file += "  TensorInputsFloat *InTensor;\n"
    file += "  float *csr_x;\n"
    file += "  void setup() override { this->St->OtherStats[\"NTile\"] = {4}; }\n\n"
    file += "  void preExecute() override {}\n\n"
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "    t1.start();\n\n"
    file += "    spmv_csr_float(InTensor->M, InTensor->ACsr->p, InTensor->ACsr->i, csr_x,\n"
    file += "                   InTensor->Bx, OutTensor->Dx);\n\n"
    file += "    t1.stop();\n"
    file += "    return t1;\n"
    file += "  }\n\n"
    file += "  bool verify(double &Error) override {\n"
    file += "    bool retValue = true;\n"
    file += "    if (!InTensor->IsSolProvided) {\n"
    file += "      Error = 0;\n"
    file += "      return true;\n"
    file += "    }\n"
    file += "    double infNorm = 0;\n"
    file += "    for (int i = 0; i < InTensor->M - 1; ++i) {\n\n"
    file += "      if (std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]) > infNorm) {\n"
    file += "        infNorm = std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]);\n"
    file += "      }\n"
    file += "    }\n"
    file += "    Error = (double)infNorm;\n"
    file += "    if (infNorm > InTensor->Threshold) {\n"
    file += "      retValue = false;\n"
    file += "    }\n"
    file += "    return retValue;\n"
    file += "  }\n\n"
    file += "public:\n"
    file += "  TensorOutputs<float> *OutTensor;\n"
    file += "  SpMVSerialFloat(TensorInputsFloat *In1, swiftware::benchmark::Stats *Stat1)\n"
    file += "      : swiftware::benchmark::SWTensorBench<float>(In1, Stat1) {\n"
    file += "    OutTensor = new TensorOutputs<float>(In1->M);\n"
    file += "    InTensor = In1;\n"
    file += "    csr_x =\n"
    file += "        static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->nnz));\n"
    file += "    for (int i = 0; i < In1->ACsr->nnz; i++) {\n"
    file += "      csr_x[i] = static_cast<float>(In1->ACsr->x[i]);\n"
    file += "    }\n"
    file += "  };\n\n"
    file += "  virtual void envelopCalculation() {}\n\n"
    file += "  ~SpMVSerialFloat() {\n"
    file += "    delete OutTensor;\n"
    file += "    free(csr_x);\n"
    file += "  }\n"
    file += "};\n\n"

    file += "class SpMVcuSparse : public SpMVSerialFloat {\n"
    file += ""
    file += "  float *x;\n"
    file += "  int *dA_csrOffsets, *dA_columns;\n"
    file += "  float *dA_values, *dX, *dY;\n"
    file += ""
    file += "  // CUSPARSE APIs\n"
    file += "  cusparseHandle_t handle = NULL;\n"
    file += "  cusparseSpMatDescr_t matA;\n"
    file += "  cusparseDnVecDescr_t vecX, vecY;\n"
    file += "  void *dBuffer = NULL;\n"
    file += "  size_t bufferSize = 0;\n"
    file += ""
    file += "  float alpha = 1.0f;\n"
    file += "  float beta = 0.0f;\n"
    file += ""
    file += "  bool verify(double &Error) override {\n"
    file += "    bool retValue = true;\n"
    file += "    if (!InTensor->IsSolProvided) {\n"
    file += "      Error = 0;\n"
    file += "      return true;\n"
    file += "    }\n"
    file += "    double infNorm = 0;\n"
    file += "    for (int i = 0; i < InTensor->M - 1; ++i) {\n"
    file += ""
    file += "      if (std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]) > infNorm) {\n"
    file += "        infNorm = std::abs(OutTensor->Dx[i] - InTensor->CorrectMul[i]);\n"
    file += "      }\n"
    file += "    }\n"
    file += "    Error = (double)infNorm;\n"
    file += "    if (infNorm > InTensor->Threshold) {\n"
    file += "      retValue = false;\n"
    file += "    }\n"
    file += "    return retValue;\n"
    file += "  }\n"
    file += ""
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += ""
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "    t1.startGPU();\n"
    file += "    cusparseSpMV(handle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha, matA, vecX,\n"
    file += "                 &beta, vecY, CUDA_R_32F, CUSPARSE_SPMV_ALG_DEFAULT, dBuffer);\n"
    file += "    t1.stopGPU(\"\");\n"
    file += ""
    file += "    cudaMemcpy(this->OutTensor->Dx, dY, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyDeviceToHost);\n"
    file += ""
    file += "    return t1;\n"
    file += "  }\n"
    file += ""
    file += "public:\n"
    file += "  SpMVcuSparse(TensorInputsFloat *In1, swiftware::benchmark::Stats *Stat1)\n"
    file += "      : SpMVSerialFloat(In1, Stat1) {\n"
    file += "    x = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->nnz));\n"
    file += "    for (int i = 0; i < In1->ACsr->nnz; i++) {\n"
    file += "      x[i] = static_cast<float>(In1->ACsr->x[i]);\n"
    file += "    }\n"
    file += ""
    file += "    cudaMalloc((void **)&dA_csrOffsets,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_columns, this->InTensor->ACsr->nnz * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_values, this->InTensor->ACsr->nnz * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dX, this->InTensor->ACsr->n * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY, this->InTensor->ACsr->m * sizeof(float));\n"
    file += ""
    file += "    cudaMemcpy(dA_values, this->x, this->InTensor->ACsr->nnz * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_csrOffsets, this->InTensor->ACsr->p,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_columns, this->InTensor->ACsr->i,\n"
    file += "               this->InTensor->ACsr->nnz * sizeof(int), cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dX, this->InTensor->Bx, this->InTensor->ACsr->n * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dY, OutTensor->Dx, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += ""
    file += "    cusparseCreate(&handle);\n"
    file += "    cusparseCreateCsr(&matA, this->InTensor->ACsr->m, this->InTensor->ACsr->n,\n"
    file += "                      this->InTensor->ACsr->nnz, dA_csrOffsets, dA_columns,\n"
    file += "                      dA_values, CUSPARSE_INDEX_32I, CUSPARSE_INDEX_32I,\n"
    file += "                      CUSPARSE_INDEX_BASE_ZERO, CUDA_R_32F);\n"
    file += "    cusparseCreateDnVec(&vecX, this->InTensor->ACsr->n, dX, CUDA_R_32F);\n"
    file += "    cusparseCreateDnVec(&vecY, this->InTensor->ACsr->m, dY, CUDA_R_32F);\n"
    file += "    cusparseSpMV_bufferSize(handle, CUSPARSE_OPERATION_NON_TRANSPOSE, &alpha,\n"
    file += "                            matA, vecX, &beta, vecY, CUDA_R_32F,\n"
    file += "                            CUSPARSE_SPMV_ALG_DEFAULT, &bufferSize);\n"
    file += "    cudaMalloc(&dBuffer, bufferSize);\n"
    file += "  }\n"
    file += "  ~SpMVcuSparse() {\n"
    file += ""
    file += "    free(x);\n"
    file += "    cusparseDestroySpMat(matA);\n"
    file += "    cusparseDestroyDnVec(vecX);\n"
    file += "    cusparseDestroyDnVec(vecY);\n"
    file += "    cusparseDestroy(handle);\n"
    file += "    cudaFree(dBuffer);\n"
    file += "    cudaFree(dA_csrOffsets);\n"
    file += "    cudaFree(dA_columns);\n"
    file += "    cudaFree(dA_values);\n"
    file += "    cudaFree(dX);\n"
    file += "    cudaFree(dY);\n"
    file += "  }\n"
    file += "};\n"

    file += "class SpMVcuBlas : public SpMVSerialFloat {\n"
    file += "\n"
    file += "  float *dA, *dX, *dY;\n"
    file += "  float alpha = 1.0f;\n"
    file += "  float beta = 0.0f;\n"
    file += "\n"
    file += "  cublasHandle_t cublasH = NULL;\n"
    file += "  cudaStream_t stream = NULL;\n"
    file += "  const int incx = 1;\n"
    file += "  const int incy = 1;\n"
    file += "  cublasOperation_t transa = CUBLAS_OP_N;\n"
    file += "\n"
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += "\n"
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "    t1.startGPU();\n"
    file += "    CUBLAS_CHECK(cublasSgemv(cublasH, transa, InTensor->ACsr->m,\n"
    file += "                             InTensor->ACsr->n, &alpha, dA, InTensor->ACsr->m,\n"
    file += "                             dX, incx, &beta, dY, incy));\n"
    file += "    t1.stopGPU(\"\");\n"
    file += "    cudaMemcpy(this->OutTensor->Dx, dY, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyDeviceToHost);\n"
    file += ""
    file += "    return t1;\n"
    file += "  }\n"
    file += ""
    file += "public:\n"
    file += "  SpMVcuBlas(TensorInputsFloat *In1, swiftware::benchmark::Stats *Stat1)\n"
    file += "      : SpMVSerialFloat(In1, Stat1) {\n"
    file += "\n"
    file += "    cublasCreate(&cublasH);\n"
    file += "\n"
    file += "    // transpose the matrix\n"
    file += "    float *NA = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->m * In1->ACsr->n));\n"
    file += "    generateDenseFromCsr(In1->ACsr->m, In1->ACsr->n, In1->ACsr, NA);\n"
    file += "\n"
    file += "    float *Trans_NA = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->m * In1->ACsr->n));\n"
    file += "    for (int i = 0; i < In1->ACsr->m; i++) {\n"
    file += "      for (int j = 0; j < In1->ACsr->n; j++) {\n"
    file += "        Trans_NA[j * In1->ACsr->m + i] = NA[i * In1->ACsr->n + j];\n"
    file += "      }\n"
    file += "    }\n"
    file += "\n"
    file += "    cudaMalloc(&dA, sizeof(float) * In1->ACsr->m * In1->ACsr->n);\n"
    file += "    cudaMalloc((void **)&dX, this->InTensor->ACsr->n * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "\n"
    file += "    cudaMemcpy(dA, Trans_NA, sizeof(float) * In1->ACsr->m * In1->ACsr->n,\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dX, this->InTensor->Bx, sizeof(float) * In1->ACsr->n,\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "    free(NA);\n"
    file += "    free(Trans_NA);\n"
    file += "  };\n"
    file += "\n"
    file += "  ~SpMVcuBlas() {\n"
    file += ""
    file += "    /* free resources */\n"
    file += "    cudaFree(dA);\n"
    file += "    cudaFree(dX);\n"
    file += "    cudaFree(dY);\n"
    file += ""
    file += "    cublasDestroy(cublasH);\n"
    file += "\n"
    file += "    cudaStreamDestroy(stream);\n"
    file += "\n"
    file += "    cudaDeviceReset();\n"
    file += "  }\n"
    file += "};\n"

    file += "template <typename T, int THREADS_PER_VECTOR>\n"
    file += "__global__ void spmv_complex_kernel(int *d_ptr, int *d_cols, T *d_val,\n"
    file += "                                    T *d_vector, T *d_out, int N) {\n"
    file += "  int laneId = threadIdx.x % THREADS_PER_VECTOR; // Lane index in the vector\n"
    file += "  int vectorId = threadIdx.x / THREADS_PER_VECTOR; // Vector index in the thread block\n"
    file += "  int warpLaneId = threadIdx.x % 32;    // Lane index in the warp\n"
    file += "  int warpVectorId = warpLaneId / THREADS_PER_VECTOR; // Vector index in the warp\n"
    file += "  __shared__ volatile int space[THREADS_PER_VECTOR][2];\n"
    file += "  int blockRows = (N + gridDim.x - 1) / gridDim.x;\n"
    file += "  int startRow = blockIdx.x * blockRows;\n"
    file += "  int endRow = min(startRow + blockRows, N);\n"
    file += "  for (int row = startRow + warpVectorId; row < endRow;\n"
    file += "       row += 32 / THREADS_PER_VECTOR) {\n"
    file += "    if (laneId < 2) {\n"
    file += "      space[vectorId][laneId] = d_ptr[row + laneId];\n"
    file += "    }\n"
    file += "    int rowStart = space[vectorId][0];\n"
    file += "    int rowEnd = space[vectorId][1];\n"
    file += "    T sum = 0;\n"
    file += "    for (int i = rowStart + laneId; i < rowEnd; i += THREADS_PER_VECTOR) {\n"
    file += "      sum += d_val[i] * d_vector[d_cols[i]];\n"
    file += "    }\n"
    file += "    for (int i = THREADS_PER_VECTOR >> 1; i > 0; i >>= 1) {\n"
    file += "      sum += __shfl_down_sync(0xffffffff, sum, i);\n"
    file += "    }\n"
    file += "    if (laneId == 0) {\n"
    file += "      d_out[row] += sum;\n"
    file += "    }\n"
    file += "  }\n"
    file += "}\n"

    file += "template <typename T>\n"
    file += "__global__ void spmv_complex_kernel_v2(int *d_ptr, int *d_cols, T *d_val,\n"
    file += "                                    T *d_vector, T *d_out, int N) {\n"
    file += "  int THREADS_PER_VECTOR = 32;\n"
    file += "  int laneId = threadIdx.x % THREADS_PER_VECTOR; // Lane index in the vector\n"
    file += "  int vectorId = threadIdx.x / THREADS_PER_VECTOR; // Vector index in the thread block\n"
    file += "  int warpLaneId = threadIdx.x % 32;    // Lane index in the warp\n"
    file += "  int warpVectorId = warpLaneId / THREADS_PER_VECTOR; // Vector index in the warp\n"
    file += "  __shared__ volatile int space[32][2];\n"
    file += "  int blockRows = 1;\n"
    file += "  int startRow = blockIdx.x * 3 + vectorId;\n"
    file += "  int endRow = min(startRow + blockRows, N);\n"
    file += "  for (int row = startRow + warpVectorId; row < endRow;\n"
    file += "       row += 32 / THREADS_PER_VECTOR) {\n"
    file += "    if (laneId < 2) {\n"
    file += "      space[vectorId][laneId] = d_ptr[row + laneId];\n"
    file += "    }\n"
    file += "    int rowStart = space[vectorId][0];\n"
    file += "    int rowEnd = space[vectorId][1];\n"
    file += "    T sum = 0;\n"
    file += "    for (int i = rowStart + laneId; i < rowEnd; i += THREADS_PER_VECTOR) {\n"
    file += "      sum += d_val[i] * d_vector[d_cols[i]];\n"
    file += "    }\n"
    file += "    for (int i = THREADS_PER_VECTOR >> 1; i > 0; i >>= 1) {\n"
    file += "      sum += __shfl_down_sync(0xffffffff, sum, i);\n"
    file += "    }\n"
    file += "    if (laneId == 0) {\n"
    file += "      d_out[row] += sum;\n"
    file += "    }\n"
    file += "  }\n"
    file += "}\n"
    file += "\n"
    file += "class SpMVComplexKernel : public SpMVSerialFloat {\n"
    file += "  float *x;\n"
    file += "  int *dA_csrOffsets, *dA_columns;\n"
    file += "  float *dA_values, *dX, *dY;\n"
    file += "  int *m_gpu, *n_gpu, *nnz_gpu;\n"
    file += "  int BlockDim = 256;\n"
    file += "  float alpha = 1.0f;\n"
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "    cudaFuncAttributes attr;\n"
    file += "    cudaFuncGetAttributes(&attr, spmv_complex_kernel<float, 32>);\n"
    file += "    t1.startGPU();\n"
    file += "    spmv_complex_kernel<float, 32><<<InTensor->ACsr->m, 32>>>(\n"
    file += "        dA_csrOffsets, dA_columns, dA_values, dX, dY, InTensor->ACsr->m);\n"
    file += "    t1.stopGPU(\"\");\n"
    file += "    cudaMemcpy(this->OutTensor->Dx, dY, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyDeviceToHost);\n"
    file += "    cudaMemset(m_gpu, 0, 2 * sizeof(int));\n"
    file += "    cudaMemset(dY, 0, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "    return t1;\n"
    file += "  }\n"
    file += "public:\n"
    file += "  SpMVComplexKernel(TensorInputsFloat *In1, swiftware::benchmark::Stats *Stat1)\n"
    file += "      : SpMVSerialFloat(In1, Stat1) {\n"
    file += "    x = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->nnz));\n"
    file += "    for (int i = 0; i < In1->ACsr->nnz; i++) {\n"
    file += "      x[i] = static_cast<float>(In1->ACsr->x[i]);\n"
    file += "    }\n"
    file += "    cudaMalloc((void **)&dA_csrOffsets,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_columns, this->InTensor->ACsr->nnz * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_values, this->InTensor->ACsr->nnz * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dX, this->InTensor->ACsr->n * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "    cudaMemcpy(dA_values, this->x, this->InTensor->ACsr->nnz * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_csrOffsets, this->InTensor->ACsr->p,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_columns, this->InTensor->ACsr->i,\n"
    file += "               this->InTensor->ACsr->nnz * sizeof(int), cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dX, this->InTensor->Bx, this->InTensor->ACsr->n * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dY, OutTensor->Dx, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "  };\n"
    file += "  ~SpMVComplexKernel() {\n"
    file += "    free(x);\n"
    file += "    cudaFree(dA_csrOffsets);\n"
    file += "    cudaFree(dA_columns);\n"
    file += "    cudaFree(dA_values);\n"
    file += "    cudaFree(dX);\n"
    file += "    cudaFree(dY);\n"
    file += "  }\n"
    file += "};\n\n"
    file += "class SpMVComplexKernelV2 : public SpMVSerialFloat {\n"
    file += "\n"
    file += "  float *x;\n"
    file += "  int *dA_csrOffsets, *dA_columns;\n"
    file += "  float *dA_values, *dX, *dY;\n"
    file += "\n"
    file += "  int *m_gpu, *n_gpu, *nnz_gpu;\n"
    file += "\n"
    file += "  int BlockDim = 256;\n"
    file += "  float alpha = 1.0f;\n"
    file += "\n"
    file += "  swiftware::benchmark::Timer execute() override {\n"
    file += "\n"
    file += "    OutTensor->reset();\n"
    file += "    swiftware::benchmark::Timer t1;\n"
    file += "\n"
    file += "    cudaFuncAttributes attr;\n"
    file += "    cudaFuncGetAttributes(&attr, spmv_complex_kernel<float, 32>);\n"
    file += "\n"
    file += "    t1.startGPU();\n"
    file += "\n"
    file += "    spmv_complex_kernel_v2<float><<< (InTensor->ACsr->m + 1 )/ 3, 96>>>(\n"
    file += "        dA_csrOffsets, dA_columns, dA_values, dX, dY, InTensor->ACsr->m);\n"
    file += "\n"
    file += "    t1.stopGPU(\"\");\n"
    file += "    cudaMemcpy(this->OutTensor->Dx, dY, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyDeviceToHost);\n"
    file += "    cudaMemset(m_gpu, 0, 2 * sizeof(int));\n"
    file += "    cudaMemset(dY, 0, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "\n"
    file += "    return t1;\n"
    file += "  }\n"
    file += "\n"
    file += "public:\n"
    file += "  SpMVComplexKernelV2(TensorInputsFloat *In1, swiftware::benchmark::Stats *Stat1)\n"
    file += "      : SpMVSerialFloat(In1, Stat1) {\n"
    file += "    x = static_cast<float *>(aligned_alloc(32, sizeof(float) * In1->ACsr->nnz));\n"
    file += "    for (int i = 0; i < In1->ACsr->nnz; i++) {\n"
    file += "      x[i] = static_cast<float>(In1->ACsr->x[i]);\n"
    file += "    }\n"
    file += "\n"
    file += "    cudaMalloc((void **)&dA_csrOffsets,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_columns, this->InTensor->ACsr->nnz * sizeof(int));\n"
    file += "    cudaMalloc((void **)&dA_values, this->InTensor->ACsr->nnz * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dX, this->InTensor->ACsr->n * sizeof(float));\n"
    file += "    cudaMalloc((void **)&dY, this->InTensor->ACsr->m * sizeof(float));\n"
    file += "\n"
    file += "    cudaMemcpy(dA_values, this->x, this->InTensor->ACsr->nnz * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_csrOffsets, this->InTensor->ACsr->p,\n"
    file += "               (this->InTensor->ACsr->m + 1) * sizeof(int),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dA_columns, this->InTensor->ACsr->i,\n"
    file += "               this->InTensor->ACsr->nnz * sizeof(int), cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "    cudaMemcpy(dX, this->InTensor->Bx, this->InTensor->ACsr->n * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "    cudaMemcpy(dY, OutTensor->Dx, this->InTensor->ACsr->m * sizeof(float),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "    //    CHECK_CUDA_ERROR(cudaGetLastError());\n"
    file += "  }\n"
    file += "  ~SpMVComplexKernelV2() {\n"
    file += "    free(x);\n"
    file += "    cudaFree(dA_csrOffsets);\n"
    file += "    cudaFree(dA_columns);\n"
    file += "    cudaFree(dA_values);\n"
    file += "    cudaFree(dX);\n"
    file += "    cudaFree(dY);\n"
    file += "  }\n"
    file += "};\n"

    file += "// Mixed Format\n"
    file += "struct TensorInputsMixed : public TensorInputsFloat {\n"
    file += "\n"
    file += "public:\n"
    file += "  swiftware::compression::MixedFormat<float> *MixedFormat;\n"
    file += "  TensorInputsMixed(int M1, int N1, sym_lib::CSR *A1,\n"
    file += "                    swiftware::compression::MixedFormat<float> *Mixed,\n"
    file += "                    int NumThreads1, int NumTrial1, std::string ExpN)\n"
    file += "      : TensorInputsFloat(M1, N1, A1, NumThreads1, NumTrial1, ExpN),\n"
    file += "        MixedFormat(Mixed){}\n"
    file += "};\n"

    file += "template <typename T>\n"
    file += "swiftware::compression::CompressedFormatGPU<T> *allocateAndCopyCompressedFormat(\n"
    file += "    swiftware::compression::CompressedFormat<T> *h_cf) {\n"
    file += "  swiftware::compression::CompressedFormatGPU<T> *d_cf;\n"
    file += "  cudaMalloc((void **)&d_cf,\n"
    file += "             sizeof(swiftware::compression::CompressedFormatGPU<T>));\n"
    file += "  cudaMemcpy(d_cf, h_cf, sizeof(swiftware::compression::CompressedFormat<T>),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  // Allocate and copy NNZ, cols, RPP, NPP, PT, CB, CSRRows arrays\n"
    file += "  T *d_NNZ;\n"
    file += "  int *d_cols, *d_RPP, *d_NPP;\n"
    file += "  int *d_PT, *d_CB, *d_CSRRows;\n"
    file += "\n"
    file += "  cudaMalloc((void **)&d_NNZ, h_cf->nnz * sizeof(T));\n"
    file += "  cudaMemcpy(d_NNZ, h_cf->NNZ, h_cf->nnz * sizeof(T), cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  cudaMalloc((void **)&d_RPP, h_cf->nrpp * sizeof(int));\n"
    file += "  cudaMemcpy(d_RPP, h_cf->RPP, h_cf->nrpp * sizeof(int),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  cudaMalloc((void **)&d_NPP, h_cf->nrpp * sizeof(int));\n"
    file += "  cudaMemcpy(d_NPP, h_cf->NPP, h_cf->nrpp * sizeof(int),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  cudaMalloc((void **)&d_PT, h_cf->PT.size() * sizeof(int));\n"
    file += "  cudaMemcpy(d_PT, h_cf->PT.data(), h_cf->PT.size() * sizeof(int),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  cudaMalloc((void **)&d_CB, h_cf->CB.size() * sizeof(int));\n"
    file += "  cudaMemcpy(d_CB, h_cf->CB.data(), h_cf->CB.size() * sizeof(int),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  // Update pointers in the device CompressedFormat\n"
    file += "  CUDA_CHECK(\n"
    file += "      cudaMemcpy(&(d_cf->NNZ), &d_NNZ, sizeof(T *), cudaMemcpyHostToDevice));\n"
    file += "  CUDA_CHECK(\n"
    file += "      cudaMemcpy(&(d_cf->RPP), &d_RPP, sizeof(int *), cudaMemcpyHostToDevice));\n"
    file += "  cudaMemcpy(&(d_cf->NPP), &d_NPP, sizeof(int *), cudaMemcpyHostToDevice);\n"
    file += "  cudaMemcpy(&(d_cf->PT), &d_PT, sizeof(int *), cudaMemcpyHostToDevice);\n"
    file += "  cudaMemcpy(&(d_cf->CB), &d_CB, sizeof(int *), cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  return d_cf;\n"
    file += "}\n"
    file += "template <typename T>\n"
    file += "swiftware::compression::MixedFormatGPU<T> *\n"
    file += "allocateAndCopyMixedFormat(swiftware::compression::MixedFormat<T> *h_mixed) {\n"
    file += "\n"
    file += "  swiftware::compression::MixedFormatGPU<T> *d_mixed;\n"
    file += "  cudaMalloc((void **)&d_mixed,\n"
    file += "             sizeof(swiftware::compression::MixedFormatGPU<T> *));\n"
    file += "\n"
    file += "  // Allocate and copy the array of CompressedFormat pointers\n"
    file += "  swiftware::compression::CompressedFormatGPU<T> **d_cf;\n"
    file += "  cudaMalloc((void **)&d_cf,\n"
    file += "             h_mixed->cf.size() *\n"
    file += "                 sizeof(swiftware::compression::CompressedFormatGPU<T> *));\n"
    file += "\n"
    file += "  for (size_t i = 0; i < h_mixed->cf.size(); ++i) {\n"
    file += "    swiftware::compression::CompressedFormatGPU<T> *d_cf_element =\n"
    file += "        allocateAndCopyCompressedFormat(h_mixed->cf[i]);\n"
    file += "    cudaMemcpy(&(d_cf[i]), &d_cf_element,\n"
    file += "               sizeof(swiftware::compression::CompressedFormatGPU<T> *),\n"
    file += "               cudaMemcpyHostToDevice);\n"
    file += "  }\n"
    file += "\n"
    file += "  cudaMemcpy(&(d_mixed->cf), &d_cf,\n"
    file += "             sizeof(swiftware::compression::CompressedFormatGPU<T> *),\n"
    file += "             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  //  int cf_len = h_mixed->cf.size();\n"
    file += "  //  cudaMemcpy(&(d_mixed->cflen), &cf_len, sizeof(int *),\n"
    file += "  //  cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  // Allocate and copy the CSRFormat\n"
    file += "  //  swiftware::compression::CSRFormatGPU<T> *d_csr =\n"
    file += "  //      allocateAndCopyCSRFormat(h_mixed->csr);\n"
    file += "  //  cudaMemcpy(&(d_mixed->csr), &d_csr,\n"
    file += "  //             sizeof(swiftware::compression::CSRFormatGPU<T> *),\n"
    file += "  //             cudaMemcpyHostToDevice);\n"
    file += "\n"
    file += "  return d_mixed;\n"
    file += "}\n"

    file += codelet_file
    file += "\n"
    file += kernel_file
    file += "\n"
    file += class_file

    file += "#endif // COMPRESSED_TENSOR_ALGEBRA_SPMV_DEMO_GPU_UTILS_H\n"

    return file
